In [70]:
import tensorflow as tf

In [71]:
import numpy as np
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
m, n = housing.data.shape
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]

In [72]:
n_epochs = 1000
learning_rate = 0.01

## Manually Computing the Gradients

In [78]:
tf.reset_default_graph()
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
best_theta

Epoch 0 MSE = 3.765896
Epoch 100 MSE = 0.62296236
Epoch 200 MSE = 0.56571186
Epoch 300 MSE = 0.55582047
Epoch 400 MSE = 0.5491339
Epoch 500 MSE = 0.54399633
Epoch 600 MSE = 0.5399965
Epoch 700 MSE = 0.5368641
Epoch 800 MSE = 0.5343983
Epoch 900 MSE = 0.5324483


array([[ 2.0685523 ],
       [ 0.8914271 ],
       [ 0.14412208],
       [-0.35652474],
       [ 0.36960667],
       [ 0.00392374],
       [-0.04279017],
       [-0.6568984 ],
       [-0.63350034]], dtype=float32)

## Using autodiff

In [79]:
tf.reset_default_graph()
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0] ############ AUTO-DIFF
training_op = tf.assign(theta, theta - learning_rate * gradients)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
best_theta

Epoch 0 MSE = 9.493296
Epoch 100 MSE = 0.8330091
Epoch 200 MSE = 0.6594612
Epoch 300 MSE = 0.61924964
Epoch 400 MSE = 0.5929202
Epoch 500 MSE = 0.57402176
Epoch 600 MSE = 0.56036043
Epoch 700 MSE = 0.5504753
Epoch 800 MSE = 0.5433184
Epoch 900 MSE = 0.5381344


array([[ 2.0685523 ],
       [ 0.8018941 ],
       [ 0.15170018],
       [-0.14179459],
       [ 0.17200187],
       [ 0.00784241],
       [-0.04152215],
       [-0.6857277 ],
       [-0.6497047 ]], dtype=float32)

## Using an optimizer

In [81]:
tf.reset_default_graph()
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n+1,1],-1.0,1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) #### OPTIMIZER
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
best_theta

Epoch 0 MSE = 8.043779
Epoch 100 MSE = 0.7189225
Epoch 200 MSE = 0.58542204
Epoch 300 MSE = 0.5667056
Epoch 400 MSE = 0.5548421
Epoch 500 MSE = 0.54633456
Epoch 600 MSE = 0.54019964
Epoch 700 MSE = 0.53577495
Epoch 800 MSE = 0.532583
Epoch 900 MSE = 0.5302809


array([[ 2.0685523 ],
       [ 0.7920578 ],
       [ 0.13758503],
       [-0.14616196],
       [ 0.18570718],
       [ 0.00283554],
       [-0.04011846],
       [-0.79786426],
       [-0.7618065 ]], dtype=float32)